export enum LEVELS {
  TrialRound = "TrialRound",
  Round1 = "round1",
  Round2 = "round2",
  SemiFinal = "semiFinal",
  Final = "final",
  AdditionalWords = "Additional Words",
}
export enum STAGES {
  kids = "kids",
  junior = "junior",
  senior = "senior",
  absolute = "absolute",
  super = "super",
}
interface WordData {
  [LEVELS.TrialRound]?: string[];
  [LEVELS.Round1]?: string[];
  [LEVELS.Round2]?: string[];
  [LEVELS.SemiFinal]?: string[];
  [LEVELS.Final]?: string[];
  [LEVELS.AdditionalWords]?: string[];
}

type Words = Record<string, WordData>;

export const words: Words = {
  kids: {
    [LEVELS.Round1]: [
      "let",
      "find",
      "hate",
      "keep",
      "stay",
      "take",
      "down",
      "sing",
      "grow",
      "call",
      "help",
      "join",
      "make",
      "dry",
      "low",
      "old",
      "soft",
      "ugly",
      "easy",
      "open",
      "fast",
      "tall",
      "wet",
      "busy",
      "cold",
      "free",
      "hot",
      "ill",
      "kind",
      "late",
      "egg",
      "fish",
      "milk",
      "soup",
      "June",
      "July",
      "fox",
      "lion",
      "wolf",
      "crab",
      "chin",
      "nail",
      "lip",
      "nose",
      "arm",
      "back",
      "foot",
      "hand",
      "leg",
      "eat",
      "find",
      "fall",
      "love",
      "get",
      "move",
      "coat",
      "boot",
      "baby",
      "grey",
      "slim",
      "shy",
      "flat",
      "hall",
      "door",
      "gate",
      "oven",
      "tap",
      "lamp",
      "sofa",
      "lazy",
      "rug",
      "cake",
      "cook",
      "desk",
      "golf",
      "chop",
      "jug",
      "nut",
      "rose",
      "true",
      "bite",
      "cry",
      "draw",
      "sit",
      "read",
      "pay",
      "swim",
      "cut",
      "tell",
      "ask",
      "fail",
      "kick",
      "look",
      "map",
      "bag",
      "song",
      "step",
      "blue",
      "pink",
      "dish",
      "jump ",
      "camp",
      "rock",
      "bell",
      "drum",
      "ring",
      "shop",
      "frog",
      "doll",
      "say",
      "lake",
      "stop",
      "moon",
      "king",
      "snow",
      "fire",
      "gift ",
      "ball",
      "big",
      "park",
      "left",
      "game",
      "same",
      "push",
      "pull ",
    ],
    [LEVELS.SemiFinal]: [
      "father",
      "mother",
      "sister",
      "uncle",
      "bottom",
      "chest",
      "elbow",
      "finger",
      "brush",
      "catch",
      "finish",
      "sleep",
      "child",
      "short",
      "young",
      "happy",
      "polite",
      "block",
      "house",
      "hotel",
      "garden",
      "fence",
      "stove",
      "carpet",
      "table",
      "baker",
      "farmer",
      "pilot",
      "chair",
      "printer",
      "tennis",
      "camera",
      "apple",
      "lemon",
      "river",
      "windy",
      "donkey",
      "goose",
      "puppy",
      "rabbit",
      "kitten",
      "camel",
      "shark",
      "tiger",
      "zebra",
      "snail",
      "snake",
      "spider",
      "build",
      "drink",
      "smile",
      "paint",
      "shake",
      "teach",
      "speak",
      "close",
      "about",
      "adult",
      "dinner",
      "lunch",
      "break",
      "shower",
      "phone",
      "watch",
      "drive",
      "shoes",
      "socks",
      "dress",
      "brush",
      "clock",
      "floor",
      "pillow",
      "clean",
      "window",
      "bottle",
      "radio",
      "video",
      "actor",
      "driver",
      "agent",
      "orange",
      "carrot",
      "tomato",
      "bread",
      "butter",
      "water",
      "potato",
      "cheese",
      "April",
      "winter",
      "small",
      "brave",
      "bright",
      "clever",
      "funny",
      "melon",
      "empty",
      "doctor",
      "forget",
      "learn",
      "smell",
      "start",
      "travel",
      "above",
      "street",
      "piano",
      "horse",
      "candle",
      "animal",
      "school",
      "tunnel",
      "rocket",
      "pirate",
      "puzzle",
      "ribbon",
      "spirit",
      "soccer",
      "summer",
      "flight",
      "forest",
      "ticket",
      "bridge",
      "planet",
      "jungle",
      "clown",
      "drive",
      "stand",
      "nurse",
      "garage",
      "museum ",
      "market",
      "Canada",
      "Africa",
      "France ",
      "Germany ",
      "Japan",
      "Greece",
      "surfing",
      "golden",
      "hungry ",
      "angry",
      "scared",
      "strict ",
      "mango",
      "koala",
    ],
    [LEVELS.Final]: [
      "brother",
      "children",
      "daughter",
      "grandfather",
      "grandmother",
      "eyelashes",
      "shoulder",
      "raincoat",
      "umbrella",
      "breakfast",
      "caravan",
      "French",
      "trousers",
      "beautiful",
      "handsome",
      "American",
      "between",
      "supermarket",
      "station",
      "restaurant",
      "outside",
      "fireplace",
      "painting",
      "television",
      "toothbrush",
      "toothpaste",
      "decorate",
      "balcony",
      "bathroom",
      "kitchen",
      "bookcase",
      "electricity",
      "fireman",
      "policeman",
      "postman",
      "teacher",
      "translator",
      "basketball",
      "volleyball",
      "dentist",
      "actress",
      "calculator",
      "calendar",
      "computer",
      "stapler",
      "telephone",
      "football",
      "waterfall",
      "camping",
      "fishing",
      "coconut",
      "pineapple",
      "cucumber",
      "beetroot",
      "cabbage",
      "mushroom",
      "sausages",
      "ketchup",
      "watermelon",
      "apricot",
      "marmalade",
      "January",
      "September",
      "October",
      "November",
      "December",
      "autumn",
      "blizzard",
      "drizzle",
      "hamster",
      "dolphin",
      "elephant",
      "giraffe",
      "hedgehog",
      "kangaroo",
      "volcano",
      "village",
      "octopus",
      "ladybird",
      "butterfly",
      "expensive",
      "comfortable",
      "chicken",
      "important",
      "promise",
      "subscribe",
      "married",
      "agree",
      "against",
      "describe",
      "explain",
      "deliver",
      "blanket",
      "remember",
      "understand",
      "patient",
      "armchair",
      "difficult",
      "husband",
      "eyebrow",
      "banana",
      "monkey",
      "balloon",
      "diamond",
      "battery",
      "chocolate",
      "hospital",
      "backpack",
      "mountain",
      "sunshine",
      "vacation",
      "airplane",
      "building",
      "learning",
      "medicine",
      "rainbow",
      "melody",
      "horizon",
      "daytime",
      "holiday",
      "victory",
      "acrobat",
      "fantasy",
      "balance",
      "leopard",
      "dancer ",

      "uniform",
      "sunrise",
      "palace",
      "harvest",
      "insect",
      "wishing",
      "captain",
      "keyhole",
      "kingdom",
      "window ",
      "library",
      "amazing",
      "beautiful",
      "wonderful",
      "support",
      "design ",
      "success",
      "critical",
      "running",
      "healthy ",
      "reading ",
      "creative",
      "skillful ",
      "greatest ",
      "control ",
      "special ",
      "charger",
      "planning",
      "vacuum ",
      "tomorrow",
      "meeting ",
      "student ",
      "distance ",
      "factory ",
      "activity",
      "discuss",
      "original ",
      "welcome",
      "positive",
      "negative ",
      "freedom ",
      "central ",
      "perfect ",
    ],
    [LEVELS.AdditionalWords]: [
      "absence",
      "acquaintance",
      "conscious",
      "difference",
      "existence",
      "genius",
      "imitate",
      "lightning",
      "necessary",
      "parliament",
      "pleasant",
      "raspberry",
      "tattoo",
      "accelerate",
      "acquire",
      "barbecue",
      "candidate",
      "definitely",
      "embarrass",
      "explanation",
      "inadvertent",
      "marshmallow",
      "noticeable",
      "journalist",
      "ambitious",
      "photographer",
      "particular",
      "receive",
      "tomorrow",
      "accomplish",
      "acquit",
      "beginning",
      "coliseum",
      "criticize",
      "against",
      "environment",
      "kaleidoscope",
      "parallel",
      "desiccate",
      "handkerchief",
      "deterrence",
      "occurrence",
      "peninsula",
      "sincerely",
      "millennium",
      "mischievous",
      "rhythm",
      "government",
      "beginning",
      "occasion ",
      "cliché",
      "protein",
      "radiant",
      "oasis",
      "analysis",
      "obesity",
      "council",
      "pressure",
      "athlete",
      "apology",
      "vitamin",
      "bankrupt",
      "voucher",
      "asthma",
      "technically",
      "Bravado ",
      "Combative ",
      "Esoteric ",
      "Felicity ",
      "Fanatical ",
      "Gullible ",
      "Humility ",
      "Imperative ",
      "Obstinate ",
      "Opulent ",
      "Palpable ",
      "Peculiar ",
      "Perception ",
      "Perilous ",
      "Petrify ",
      "Pinnacle ",
      "Plethora ",
      "Pompous ",
      "Precedent ",
      "Pragmatic ",
      "Precarious ",
      "Ponderous ",
      "Prevalent ",
      "Pristine ",
      "Prodigal ",
      "Prolific ",
      "Propensity ",
      "Prudent ",
      "Quibble ",
      "Rapture ",
      "Rebellion ",
      "Refrain ",
      "Redundant ",
      "Renounce ",
      "Resolute ",
      "Reticent ",
      "Sardonic ",
      "Skeptical ",
      "Stagnant ",
      "Stalwart ",
      "Surmount ",
      "Tangible ",
      "Terminate ",
      "Transcend ",
      "Trepidation ",
      "Tyranny ",
      "Turmoil ",
      "Unassuming ",
      "Uncanny ",
      "Upheaval ",
      "Regimen ",
      "Penchant ",
      "Obstinate ",
      "Nonchalant ",
      "Mundane ",
      "Larceny ",
      "Jaunty ",
      "Imminent ",
      "Hysteria ",
      "Deftness ",
      "Bucolic ",
      "parachute",
      "gymnasium",
      "integrity",
      "diagnosis",
      "rehearsal",
      "confiscate",
      "critique",
      "amateur",
      "apostrophe",
      "proprietor",
      "continuum",
      "approach ",
      "associate ",
      "chronology ",
    ],
  },
  junior: {
    [LEVELS.TrialRound]: [
      "dark",
      "find",
      "hate",
      "take",
      "down",
      "road",
      "sing",
      "grow",
      "call",
      "help",
      "join",
      "make",
      "soft",
      "ugly",
      "easy",
      "open",
      "fast",
      "tall",
      "hard",
      "busy",
      "cold",
      "deep",
      "free",
      "kind",
      "late",
      "long",
      "fish",
      "milk",
      "find",
      "flat",
      "door",
      "nail",
      "neck",
      "nose",
      "brush",
      "back",
      "foot",
      "hand",
      "head",
      "move",
      "fire",
      "lamp",
      "sofa",
      "oven",
      "shelf",
      "bread",
      "friend ",
      "ticket",
      "check ",
      "plate ",
      "pilot ",
      "bake",
      "cake",
      "cook",
      "dark",
      "grey",
      "long",
      "slim",
      "tall",
      "lazy",
      "loud",
      "read",
      "start",
      "fall",
      "chin",
      "map",
      "cry",
      "egg",
      "fox",
      "get",
    ],
    [LEVELS.Round1]: [
      "father",
      "travel",
      "mother",
      "parent",
      "sister",
      "uncle",
      "throat",
      "chest",
      "elbow",
      "finger",
      "brush",
      "catch",
      "finish",
      "sleep",
      "smell",
      "start",
      "young",
      "happy",
      "polite",
      "boring",
      "block",
      "house",
      "hotel",
      "garden",
      "fence",
      "garage",
      "stove",
      "fridge",
      "knife",
      "baker",
      "farmer",
      "pilot",
      "chair",
      "printer",
      "tennis",
      "camera",
      "banana",
      "lemon",
      "build",
      "carry",
      "dream",
      "sunny",
      "windy",
      "breeze",
      "chilly",
      "goose",
      "puppy",
      "rabbit",
      "kitten",
      "camel",
      "monkey",
      "shark",
      "tiger",
      "zebra",
      "snail",
      "snake",
      "spider",
      "river",
      "dirty",
      "shout",
      "smile",
      "count",
      "fight",
      "paint",
      "shake",
      "teach",
      "speak",
      "close",
      "reply",
      "study",
      "dinner",
      "lunch",
      "break",
      "shower",
      "listen",
      "phone",
      "watch",
      "become",
      "drive",
      "shoes",
      "socks",
      "dress",
      "about",
      "brush",
      "clock",
      "floor",
      "pillow",
      "clean",
      "window",
      "bottle",
      "video",
      "nurse",
      "forget",
      "learn",
      "orange",
      "carrot",
      "onion",
      "tomato",
      "water",
      "cheese",
      "March",
      "summer",
      "month",
      "cloudy",
      "agree",
      "brave",
      "bright",
      "clever",
      "funny",
      "hungry",
      "modern",
      "tired",
      "misty",
      "upset",
      "behind",
      "across",
      "inside",
      "melon",
      "empty",
      "frosty",
      "follow",
      "frank",
      "proud",
      "client",
      "angry",
      "lonely",
      "artist",
      "stage",
      "wings",
      "critic",
      "comedy",
      "drama",
      "attend",
      "punish",
      "title",
      "formal",
      "canoe",
      "heater",
      "speed",
      "ticket",
      "motel",
      "capital",
      "village",
      "circle",
      "danger",
      "refuse",
      "invent",
      "invite",
      "active",
      "nation",
      "poison",
      "south",
      "silent",
      "profit",
      "vanish",
      "trust",
      "cause",
      "shine",
      "worry",
      "borrow",
      "fasten",
      "obey",
      "afford",
      "defend",
      "candle",
      "renew",
      "unpack",
    ],
    [LEVELS.SemiFinal]: [
      "brother",
      "children",
      "daughter",
      "shoulder",
      "stomach",
      "backbone",
      "raincoat",
      "trainers",
      "umbrella",
      "handbag",
      "breakfast",
      "selfish",
      "between",
      "station",
      "opposite",
      "caravan",
      "trousers",
      "beautiful",
      "handsome",
      "sociable",
      "American",
      "Brazilian",
      "Canadian",
      "French",
      "Turkish",
      "teenager",
      "glasses",
      "actress",
      "balcony",
      "bathroom",
      "kitchen",
      "outside",
      "dishwasher",
      "fireplace",
      "painting",
      "television",
      "wallpaper",
      "radiator",
      "shampoo",
      "toothbrush",
      "toothpaste",
      "decorate",
      "important",
      "dentist",
      "microwave",
      "electricity",
      "fireman",
      "policeman",
      "postman",
      "assistant",
      "teacher",
      "translator",
      "builder",
      "badminton",
      "cricket",
      "camping",
      "fishing",
      "secretary",
      "calculator",
      "calendar",
      "mechanic",
      "computer",
      "stapler",
      "telephone",
      "football",
      "bicycle",
      "promise",
      "sausages",
      "ketchup",

      "porridge",
      "biscuits",
      "watermelon",
      "apricot",
      "marmalade",
      "January",
      "February",
      "September",
      "avocado",
      "coconut",
      "grapefruit",
      "pineapple",
      "cucumber",
      "cabbage",
      "mushroom",
      "waterfall",
      "recognize",
      "hamster",
      "dolphin",
      "elephant",
      "giraffe",
      "hedgehog",
      "kangaroo",
      "volcano",
      "village",
      "scorpion",
      "ladybird",
      "autumn",
      "spring",
      "blizzard",
      "raining",
      "snowing",
      "penguin",
      "cycling",
      "straight",
      "subscribe",
      "butterfly",
      "expensive",
      "comfortable",
      "foreign",
      "cornflakes",
      "chicken",
      "amusing",
      "emotional",
      "October",
      "friendly",
      "greedy",
      "honest",
      "speedboat",
      "present",
      "subway",
      "traffic",
      "company",
      "director",
      "season",
      "careful",
      "famous",
      "borrow",
      "greedy",
      "honest",
      "gossip",
      "column",
      "editor",
      "grandchildren",
      "grandfather",
      "grandmother",
      "eyelashes",
      "restaurant",
      "vacuum",
      "August",
      "supermarket",
      "history",
      "resume",
      "human",
      "distant",
      "update",
      "subject",
      "atlas",
      "musical",
      "article",
      "fiction",
      "chapter",
      "logical",
      "fantasy",
      "western",
      "basketball",
      "weather",
    ],
    [LEVELS.Final]: [
      "civilian",
      "nationalist",
      "anarchist",
      "arbitrator",
      "beneficiary",
      "bystander",
      "sponger",
      "mystery",
      "entertain",
      "seminar",
      "considerate",
      "require",
      "inquire",
      "purchase",
      "demolish",
      "successful",
      "apologize",
      "scream",
      "escape",
      "multiply",
      "prosecution",
      "negotiation",
      "agnostic",
      "excellent",
      "synonym",
      "antonym",
      "depress",
      "geography",
      "mathematics",
      "literature",
      "chemistry",
      "physics",
      "language",
      "mixture",
      "keyboard",
      "graduation",
      "recruit",
      "balance",
      "describe",
      "discuss",
      "educate",
      "pronounce",
      "suggest",
      "explode",
      "medicine",
      "pretend",
      "confess",
      "whisper",
      "specialize",
      "expected",
      "consistent",
      "fortunately",
      "literate",
      "accident",
      "relevant",
      "politics",
      "attract",
      "ambition",
      "success",
      "horrible",
      "healthy",
      "profession",
      "translate",
      "investment",
      "chairman",
      "responsible",
      "comfortable",
      "vacation",
      "autobiography",
      "dictionary",
      "encyclopedia",
      "paperback",
      "appendix",
      "bibliography",
      "contents",
      "footnote",
      "glossary",
      "interval",
      "classified",
      "crossword",
      "headline",
      "horoscope",
      "tabloid",
      "advantage",
      "dependent",
      "possible",
      "rehearsal",
      "excited",
      "guilty",
      "academic",
      "character",
      "performance",
      "adventure",
      "cartoon",
      "playground",
      "register",
      "newspaper",
      "crossroads",
      "helpless",
      "speedometer",
      "neighbour",
      "compulsory",
      "detention",
      "nervous",
      "confused",
      "carriage",
      "platform",
      "ambulance",
      "indicator",
      "advertisement",
      "windscreen",
      "guidebook",
      "brochure",
      "childish",
      "forgetful",
      "boyfriend",
      "baggage",
      "scooter",
      "intelligent",
      "optimist ",
      "celebrity",
      "interval",
      "appendix",
      "platform",
      "newspaper",
      "abstract ",
      "analogy",
      "anticipate ",
      "application",
      "associate ",
      "background",
      "complement",
      "composition",
      "conclude ",
      "consistent",
      "constitute ",
      "contradict ",
      "delicate",
      "colossal ",
      "epochal ",
      "gravitas ",
      "panacea",
      "ruminate ",
      "utopian ",
      "opulent ",
    ],
    [LEVELS.AdditionalWords]: [
      "absence",
      "acquaintance",
      "conscious",
      "difference",
      "existence",
      "genius",
      "imitate",
      "lightning",
      "necessary",
      "parliament",
      "pleasant",
      "raspberry",
      "tattoo",
      "accelerate",
      "acquire",
      "barbecue",
      "candidate",
      "definitely",
      "embarrass",
      "explanation",
      "inadvertent",
      "marshmallow",
      "noticeable",
      "journalist",
      "ambitious",
      "photographer",
      "particular",
      "receive",
      "tomorrow",
      "accomplish",
      "acquit",
      "beginning",
      "coliseum",
      "criticize",
      "against",
      "environment",
      "kaleidoscope",
      "parallel",
      "desiccate",
      "handkerchief",
      "deterrence",
      "occurrence",
      "peninsula",
      "sincerely",
      "millennium",
      "mischievous",
      "rhythm",
      "government",
      "beginning",
      "occasion ",
      "cliché",
      "protein",
      "radiant",
      "oasis",
      "analysis",
      "obesity",
      "council",
      "pressure",
      "athlete",
      "apology",
      "vitamin",
      "bankrupt",
      "voucher",
      "asthma",
      "technically",
      "Bravado ",
      "Combative ",
      "Esoteric ",
      "Felicity ",
      "Fanatical ",
      "Gullible ",
      "Humility ",
      "Imperative ",
      "Obstinate ",
      "Opulent ",
      "Palpable ",
      "Peculiar ",
      "Perception ",
      "Perilous ",
      "Petrify ",
      "Pinnacle ",
      "Plethora ",
      "Pompous ",
      "Precedent ",
      "Pragmatic ",
      "Precarious ",
      "Ponderous ",
      "Prevalent ",
      "Pristine ",
      "Prodigal ",
      "Prolific ",
      "Propensity ",
      "Prudent ",
      "Quibble ",
      "Rapture ",
      "Rebellion ",
      "Refrain ",
      "Redundant ",
      "Renounce ",
      "Resolute ",
      "Reticent ",
      "Sardonic ",
      "Skeptical ",
      "Stagnant ",
      "Stalwart ",
      "Surmount ",
      "Tangible ",
      "Terminate ",
      "Transcend ",
      "Trepidation ",
      "Tyranny ",
      "Turmoil ",
      "Unassuming ",
      "Uncanny ",
      "Upheaval ",
      "Regimen ",
      "Penchant ",
      "Obstinate ",
      "Nonchalant ",
      "Mundane ",
      "Larceny ",
      "Jaunty ",
      "Imminent ",
      "Hysteria ",
      "Deftness ",
      "Bucolic ",
      "parachute",
      "gymnasium",
      "integrity",
      "diagnosis",
      "rehearsal",
      "confiscate",
      "critique",
      "amateur",
      "apostrophe",
      "proprietor",
      "continuum",
      "approach ",
      "associate ",
      "chronology ",
    ],
  },
  senior: {
    [LEVELS.TrialRound]: [
      "blonde",
      "figure",
      "polite",
      "stupid",
      "boring",
      "block",
      "garden",
      "fence",
      "garage",
      "stove",
      "fridge",
      "scales",
      "farmer",
      "blinds",
      "diary",
      "printer",
      "squash ",
      "rugby",
      "camera",
      "apron",
      "grill",
      "kettle",
      "roast",
      "stormy",
      "windy",
      "breeze",
      "chilly",
      "donkey",
      "shout",
      "throw",
      "write",
      "climb",
      "count",
      "cycle",
      "fight",
      "paint",
      "shake",
      "sneeze",
      "builder",
      "carry",
      "cough",
      "children",
      "daughter",
      "grandchildren",
      "grandfather",
      "grandmother",
      "eyelashes",
      "forehead",
      "shoulder",
      "stomach",
      "backbone",
      "answer",
      "speak",
      "close",
      "cross",
      "knock",
      "solve",
      "spell",
      "spend",
      "reply",
      "study",
      "brush",
      "kitchen",
      "dryer",
      "clock",
      "razor",
      "floor",
      "tiles",
      "pillow",
      "sheet",
      "clean",
      "window",
      "sweep",
      "video",
      "actor",
      "driver",
      "nurse",
    ],
    [LEVELS.Round1]: [
      "balcony",
      "staircase",
      "recorder",
      "trousers",
      "beautiful",
      "raincoat",
      "slippers",
      "tracksuit",
      "trainers",
      "umbrella",
      "duvet",
      "polish",
      "bottle",
      "hammer",
      "radio",
      "torch",
      "vacuum",
      "forget",
      "shower",
      "listen",
      "phone",
      "watch",
      "become",
      "retire",
      "jacket",
      "jeans",
      "socks",
      "trunks",
      "blouse",
      "gloves",
      "adult",
      "prefer",
      "orange",
      "carrot",
      "garlic",
      "onion",
      "radish",
      "tomato",
      "sweets",
      "cheese",
      "August",
      "month",
      "season",
      "cloudy",
      "foggy",
      "reject",
      "agree",
      "frosty",
      "follow",
      "greedy",
      "honest",
      "frank",
      "proud",
      "client",
      "gossip",
      "orphan",
      "tenant",
      "angry",
      "lonely",
      "critic",
      "comedy",
      "drama",
      "attend",
      "enrol",
      "expel",
      "punish",
      "recite",
      "revise",
      "absent",
      "cover",
      "index",
      "title",
      "column",
      "editor",
      "formal",
      "common",
      "human",
      "loyal",
      "suffer",
      "sprain",
      "midwife",
      "cramp",
      "cancer",
      "sling",
      "liver",
      "skull",
      "kidney",
      "stream",
      "meadow",
      "closed",
      "narrow",
      "smooth",
      "asleep",
      "careful",
      "clever",
      "famous",
      "afraid",
      "hungry",
      "modern",
      "misty",
      "borrow",
      "upset",
      "crawl",
      "frown",
      "blink",
      "bridge",
      "canoe",
      "yacht",
      "bumper",
      "heater",
      "speed",
      "ticket",
      "capital",
      "village",
      "cruise",
      "violin",
      "circle",
      "danger",
      "differ",
      "refuse",
      "elect",
      "invent",
      "invite",
      "active",
      "govern",
      "poison",
      "sense",
      "south",
      "permit",
      "prove",
      "serve",
      "output",
      "silent",
      "profit",
      "budget",
      "helmet",
      "humble",
      "modest",
      "occur",
      "vanish",
      "trust",
      "cause",
      "shine",
      "worry",
      "borrow",
      "fasten",
      "obey",
      "afford",
      "defend",
    ],
    [LEVELS.Round2]: [
      "forehead",
      "pyjamas",
      "waistcoat",
      "cardigan",
      "handbag",
      "breakfast",
      "ambitious",
      "selfish",
      "imaginative",
      "impatient",
      "jealous",
      "backbone",
      "admire",
      "annoy",
      "dimple",
      "infant",
      "swimsuit",
      "miserable",
      "intelligent",
      "supermarket",
      "station",
      "restaurant",
      "opposite",
      "sausages",
      "chimney",
      "cupboard",
      "dishwasher",
      "ceiling",
      "fireplace",
      "curtains",
      "lampshade",
      "penalty",
      "television",
      "wallpaper",
      "pillowcase",
      "radiator",
      "shampoo",

      "toothbrush",
      "toothpaste",
      "ashtray",
      "decorate",
      "bedspread",
      "important",
      "toaster",
      "hairdresser",
      "businessman",
      "carpenter",
      "programmer",
      "dentist",
      "electrician",
      "actress",
      "journalist",
      "photographer",
      "librarian",
      "plumber",
      "secretary",
      "soldier",
      "surgeon",
      "waitress",
      "calculator",
      "calendar",
      "mechanic",
      "computer",
      "telephone",
      "bicycle",
      "sailing",
      "promise",
      "generous",
      "handsome",
      "sociable",
      "freezer",
      "American",
      "Brazilian",
      "Canadian",
      "French",
      "Turkish",
      "teenager",
      "glasses",
      "caravan",
      "cottage",
      "houseboat",
      "terrace ",
      "saucepan",
      "scissors",
      "electricity",
      "balance",
      "describe",
      "discuss",
      "educate",
      "dolphin",
      "elephant",
      "giraffe",
      "adventure",
      "cartoon",
      "playground",
      "porridge",
      "raspberry",
      "biscuits",
      "watermelon",
      "apricot",
      "marmalade",
      "January",
      "February",
      "autumn",
      "blizzard",
      "drizzle",
      "pouring",
      "penguin",
      "gymnastics",
      "straight",
      "subscribe",
      "screwdriver",
      "spanner",
      "measure",
      "dustman",
      "fireman",
      "policeman",
      "postman",
      "assistant",
      "teacher",
      "translator",
      "basketball",
      "volleyball",
      "trumpet",
      "badminton",
      "cricket",
      "quarrel",
      "cucumber",
      "collaboration",
      "windsurfing",
      "wrestling",
      "aerobics",
      "camping",
      "jogging",
      "microwave",
      "avocado",
      "blackberry",
      "coconut",
      "grapefruit",
      "pineapple",
      "helpless",
      "playground",
      "present",
      "register",
      "beetroot",
      "cabbage",
      "distant",
      "lettuce",
      "mushroom",
      "fantasy",
      "western",
      "character",
      "accordion",
      "baggage",
      "boyfriend",
      "atlas",
      "chapter",
      "hamster",
      "village",
      "interval",
      "ketchup",
      "consistent",
      "contradict",
      "annotate",
      "category",
      "calculate ",
      "brainstorm",
      "clarify ",
      "coherent",
      "compare ",
      "complement ",
      "compose ",
      "conclude",
      "concrete",
      "conduct",
      "context",
      "assume",
      "benefit",
      "collapse",
      "conflict ",
      "primary",
      "promote",
      "proximity",
      "regulate",
      "require",
      "resolve",
      "restrict",
      "rotate",
      "shelter",
      "shrink",
      "specify",
      "supervise ",
      "suspend",
      "sustain",
      "transfer ",
    ],
    [LEVELS.SemiFinal]: [
      "playwright",
      "prompter",
      "scholarship",
      "seminar",
      "preface",
      "satisfied",
      "tutorial",
      "vacation",
      "crossword",
      "dictionary",
      "directory",
      "paperback",
      "appendix",
      "bibliography",
      "expected",
      "consistent",
      "benefactor",
      "charlatan",
      "graduation",
      "recruit",
      "pronounce",
      "suggest",
      "explode",
      "medicine",
      "mystery",
      "civilian",
      "juvenile",
      "nationalist",
      "anarchist",
      "bystander",
      "sponger",
      "teetotaller",
      "castaway",

      "agnostic",
      "expatriate",
      "emotional",
      "gullible",
      "hospitable",
      "considerate",
      "disappointed",
      "embarrassed",
      "cheerful",
      "excellent",
      "geography",
      "mathematics",
      "literature",
      "chemistry",
      "physics",
      "language",
      "keyboard",
      "entertain",
      "enormous",
      "responsible",
      "comfortable",
      "tutorial",
      "vacation",
      "anthology",
      "appendix",
      "bibliography",
      "foreword",
      "glossary",
      "sensitive",
      "stubborn",
      "sympathetic",
      "talkative",
      "crossroads",
      "underpass",
      "motorway",
      "diversion",
      "performance",
      "scholarship",
      "prompter",
      "newspaper",
      "bachelor",
      "colleague",
      "neighbour",
      "courage",
      "pessimist",
      "spectator",
      "tourist",
      "vegetarian",
      "refugee",
      "survivor",
      "impulsive",
      "accelerator",
      "materialistic",
      "arrogant",
      "windpipe",
      "skeleton",
      "bandage",
      "capsule",
      "accident",
      "relevant",
      "strawberry",
      "squirrel",
      "octopus",
      "hedgehog",
      "kangaroo",
      "hurricane",
      "escape",
      "multiply",
      "investment",
      "chairman",
      "bankrupt",
      "manual",
      "paperback",
      "ashamed",
      "success",
      "expected",
      "consistent",
      "accident",
      "relevant",
      "politics",
      "courage",
      "ambition",
      "profession",
      "scorpion",
      "mosquito",
      "butterfly",
      "avalanche",
      "drought",
      "expensive",
      "terminal",
      "comfortable",
      "foreign",
      "cornflakes",
      "tabloid",
      "circulation",
      "classified",
      "feature",
      "headline",
      "horoscope",
      "advantage",
      "dependent",
      "footnote",
      "foreword",
      "glossary",
      "responsible",
      "comfortable",
      "profession",
      "experienced",
      "amusing",
      "scream",
      "obstinate",
      "require",
      "inquire",
      "purchase",
      "demolish",
      "translate",
      "stakeholder",
      "trademark",
      "negotiation",
      "dictionary",
      "directory",
      "windscreen",
      "speedometer",
      "reverse",
      "scenery",
      "sightseeing",
      "abolish",
      "justice",
      "backlash",
      "recidivist",
      "fingerprint",
      "testimony",
      "verdict",
      "defence",
      "loophole",
      "nickname",
      "windfall",
      "proverb",
      "possibility",
      "charade",
      "perimeter",
      "persuade",
      "thermometer",
      "limousine",
      "eventually",
      "vegetarian",
      "solidarity",
      "connection",
      "association",
      "relationship",
      "literature ",
      "engagement ",
      "agreement",
      "suddenly",
      "password ",
      "entrance ",
      "wireless",
      "therefore",
      "available ",
      "bashful",
      "amusing",
      "emotional",
      "complacent",
      "paranoid",
      "servant",
      "explode",
      "multiply",
      "stealing",
      "robbery",
      "looting",
      "bribery",
      "invoice",
      "interval",
      "sunshine",
      "against",
      "parallel",
      "receive",
      "lecture",
      "seize",
      "liquefy",
      "volunteer",
      "declaration ",
      "deposit ",
      "desirable",
      "dilemma ",
      "diminish ",
      "eliminate",
      "enhance ",
      "evaluate",
      "evidence ",
      "exclude",
      "expand ",
      "framework",
      "hesitate ",
      "identical ",
      "impact ",
      "implement ",
      "incidental ",
      "influence",
      "integrate",
      "interpret",
      "invasive",
      "jointly",
      "lampoon",
      "maintain",
      "maximize",
      "minimum",
      "obvious",
      "opponent",
      "oppress",
      "pragmatic",
      "precise",
      "prevalent",
      "safeguard",
      "significant",
      "sufficient",
      "transition",
      "transparent",
      "disappear ",
      "widespread ",
      "substitude ",
      "movement ",
      "particular",
      "approval",
    ],
    [LEVELS.Final]: [
      "earthquake",
      "affectionate",
      "encyclopedia",
      "tambourine",
      "breathtaking",
      "immigration",
      "picturesque",
      "correspondent",
      "autobiography",
      "illustrations",
      "encyclopedia",
      "adventurous",
      "domineering",
      "atheist",
      "scrounger",
      "malicious",
      "beneficiary",
      "outsourcing ",
      "prosecution",
      "advertisement",
      "acquaintance",
      "mantelpiece",
      "acknowledgements",
      "courageous",
      "adolescent",
      "assignment",
      "benefactor",
      "invigilator",
      "tycoon",
      "juvenile",
      "nationalist",
      "anarchist",
      "arbitrator",
      "beneficiary",
      "bystander",
      "conscript",
      "expatriate",
      "castaway",
      "scapegoat",
      "obstinate",
      "versatile",
      "casualty",
      "consultant",
      "chickenpox",
      "hepatitis",
      "bronchitis",
      "arthritis",
      "asthma",
      "malnutrition",
      "influenza",
      "insomnia",
      "antibiotics",
      "varicose",
      "terrorism",
      "diabetes",
      "fracture",
      "tranquilizer",
      "vaccination",
      "appointment",
      "pressure",
      "respiration",
      "amputate",
      "dislocate",
      "transplant",
      "disinfect",
      "quarantine",
      "blackmail",
      "pickpocketing",
      "smuggling",
      "revenue",
      "headquarters",
      "destination",
      "scenery",
      "sightseeing",
      "spectacular",
      "thriller",
      "character",
      "accordion",
      "diversion",
      "applause",
      "auditorium",
      "harbour",
      "lifeguard",
      "binoculars",
      "souvenir",
      "saxophone",
      "unconscious",
      "hijacking",
      "hyperbole",
      "blackmail",
      "adventurous",
      "amnesia",
      "boastful",
      "domineering",
      "enthusiastic",
      "gullible",
      "hospitable",
      "malicious",
      "considerate",
      "courageous",
      "stretcher",
      "thermometer",
      "tweezers",
      "wheelchair",
      "geography",
      "mathematics",
      "exhausted",
      "experienced",
      "locksmith",
      "archaeologist",
      "lumberjack",
      "solicitor",
      "taxidermist",
      "illiterate",
      "superstitious",
      "possessive",
      "anxious",
      "humiliated",
      "irritable",
      "nostalgic",
      "sentimental",
      "apprehensive",
      "speechless",
      "ambassador",
      "bailiff",
      "engineer",
      "ombudsman",
      "pawnbroker",
      "publican",
      "anorexia",
      "epilepsy",
      "inflammation",
      "circulation",
      "fortunately",
      "enormous",
      "literature",
      "chemistry",
      "physics",
      "language",
      "graduation",
      "osteopath",
      "pathologist",
      "pharmacist",
      "corruption",
      "specialist",
      "vandalism",
      "dyslexia",
      "burglary",
      "embezzlement",
      "kidnapping",
      "manslaughter",
      "shoplifting",
      "misconduct",
      "accomplice",
      "negotiation",
      "networking",
      "outsourcing ",
      "partnership",
      "migraine",
      "moustache",
      "bottleneck",
      "brainwave",
      "milestone",
      "inquest",
      "sunbathing",
      "lighthouse",
      "accordion",
      "clarinet",
      "athletics",
      "trombone",
      "harmonica",
      "audience",
      "rehearsal",
      "performance",
      "programme",
      "academic",
      "assignment",
      "compulsory",
      "detention",
      "gymnasium",
      "spectacular",
      "excursion",
      "brochure",
      "sandcastle",
      "marshmallow",
      "noticeable",
      "particular",
      "accomplish",
      "acquit",
      "beginning",
      "coliseum",
      "environment",
      "kaleidoscope",
      "lieutenant",
      "handkerchief",
      "deterrence",
      "occurrence",
      "peninsula",
      "sincerely",
      "millennium",
      "rhythm",
      "surreptitious",
      "undoubtedly",
      "thorough",
      "unmistakably",
      "questionnaire",
      "bureaucracy",
      "queue",
      "technique",
      "worthwhile",
      "conqueror",
      "beneficiary",
      "drudgery",
      "anaesthetic",
      "grandiloquent",
      "arrangement ",
      "sustainable ",
      "documentary",
      "brotherhood",
      "Philippines",
      "anniversary",
      "challenges",
      "fellowship",
      "confidence ",
      "cyberspace",
      "biodiversity",
      "companionship",
      "intermission",
      "adaptability",
      "biographical ",
      "announcement",
      "establishment",
      "sophisticated",
      "demonstrate ",
      "equivalent",
      "sequence",
      "speculate",
      "prestigious",
      "nonchalant",
      "manipulate ",
      "ridiculous ",
      "legitimate",
      "irresolute",
      "ineffective ",
      "imcompetent",
      "inclination",
      "hypothesis",
      "fundamental",
      "frivolous",
      "dispropotion",
      "diatribe ",
      "decipher",
      "cumbersome",
      "abundant ",
      "commitment ",
      "collapse ",
      "coincide ",
      "chronological ",
      "cacophony",
      "attribute ",
      "aggregate ",
      "accustomed ",
      "alacrity ",
      "amenable ",
      "anacronism ",
      "approbation",
      "aristocracy",
      "autocratic",
      "bellicose",
      "benevolent",
      "bibliophile",
      "bombastic ",
      "exaggerated ",
      "buffoon",
      "caricature",
      "clandestine",
      "coalition ",
      "collusion",
      "compatible ",
      "compensation ",
      "confederate ",
      "consensus",
      "convival ",
      "cosmopolitan",
      "devastation",
      "disparity",
      "exposition ",
    ],
    [LEVELS.AdditionalWords]: [
      "Bravado ",
      "Combative ",
      "Esoteric ",
      "Felicity ",
      "Fanatical ",
      "Gullible ",
      "Humility ",
      "Imperative ",
      "Obstinate ",
      "Opulent ",
      "Palpable ",
      "Peculiar ",
      "Perception ",
      "Perilous ",
      "Petrify ",
      "Pinnacle ",
      "Plethora ",
      "Pompous ",
      "Precedent ",
      "Pragmatic ",
      "Precarious ",
      "Ponderous ",
      "Prevalent ",
      "Pristine ",
      "Prodigal ",
      "Prolific ",
      "Propensity ",
      "Prudent ",
      "Quibble ",
      "Rapture ",
      "Rebellion ",
      "Refrain ",
      "Redundant ",
      "Renounce ",
      "Resolute ",
      "Reticent ",
      "Sardonic ",
      "Skeptical ",
      "Stagnant ",
      "Stalwart ",
      "Surmount ",
      "Tangible ",
      "Terminate ",
      "Transcend ",
      "Trepidation ",
      "Tyranny ",
      "Turmoil ",
      "Unassuming ",
      "Uncanny ",
      "Upheaval ",
      "Regimen ",
      "Penchant ",
      "Obstinate ",
      "Nonchalant ",
      "Mundane ",
      "Larceny ",
      "Jaunty ",
      "Imminent ",
      "Hysteria ",
      "Deftness ",
      "Bucolic ",
      "parachute",
      "gymnasium",
      "integrity",
      "diagnosis",
      "rehearsal",
      "confiscate",
      "critique",
      "amateur",
      "apostrophe",
      "proprietor",
      "continuum",
      "approach ",
      "associate ",
      "chronology ",
      "absence",
      "acquaintance",
      "conscious",
      "difference",
      "existence",
      "genius",
      "imitate",
      "lightning",
      "necessary",
      "parliament",
      "pleasant",
      "raspberry",
      "tattoo",
      "accelerate",
      "acquire",
      "barbecue",
      "candidate",
      "definitely",
      "embarrass",
      "explanation",
      "inadvertent",
      "marshmallow",
      "noticeable",
      "journalist",
      "ambitious",
      "photographer",
      "particular",
      "receive",
      "tomorrow",
      "accomplish",
      "acquit",
      "beginning",
      "coliseum",
      "criticize",
      "against",
      "environment",
      "kaleidoscope",
      "parallel",
      "desiccate",
      "handkerchief",
      "deterrence",
      "occurrence",
      "peninsula",
      "sincerely",
      "millennium",
      "mischievous",
      "rhythm",
      "government",
      "beginning",
      "occasion ",
      "cliché",
      "protein",
      "radiant",
      "oasis",
      "analysis",
      "obesity",
      "council",
      "pressure",
      "athlete",
      "apology",
      "vitamin",
      "bankrupt",
      "voucher",
      "asthma",
      "technically",
    ],
  },
  absolute: {
    [LEVELS.Final]: [
      "onomatopoeia",
      "ecstatic",
      "calligraphy",
      "catastrophe",
      "lexicologist",
      "unnecessary",
      "chauffeur",
      "envious",
      "obnoxious",
      "enthusiastic",
      "amphibious",
      "maneuver",
      "respirator",
      "ancestor",
      "Unfortunately",
      "cappuccino ",
      "luxurious",
      "personification",
      "embarrassed",
      "ambassador ",
      "acquisition",
      "synonymous",
      "nostalgia",
      "nauseous",
      "disappointing",
      "microorganism",
      "linguistically",
      "pseudonym",
      "cinematographer",
      "threatening",
      "arithmetician",
      "spontaneous",
      "algorithm",
      "unconscious",
      "chameleon",
      "abduction",
      "Aberration ",
      "Abundance ",
      "Acquaintance ",
      "Aggravate ",
      "Ambivalence ",
      "Ambiguous",
      "Ameliorate ",
      "Animosity",
      "Antagonist ",
      "Antithesis ",
      "Arbitrary ",
      "Arduous ",
      "Benevolent ",
      "Bewildered",
      "Boisterous ",
      "Burgeon ",
      "Buttress ",
      "Byzantine ",
      "Belligerent ",
      "Beneficiary ",
      "Catastrophe ",
      "Celestial ",
      "Clairvoyant ",
      "Camouflage ",
      "Capricious ",
      "Carnivorous ",
      "Chivalry ",
      "Colloquial ",
      "Commendable ",
      "Complicity ",
      "Conflagration ",
      "Daunting ",
      "Debilitating ",
      "Decadence ",
      "Defiance ",
      "Delirious ",
      "Demagogue ",
      "Demeanor ",
      "Derelict ",
      "Dexterity ",
      "Diabolical ",
      "Diligence ",
      "Discrepancy ",
      "Disdainful ",
      "Eloquent ",
      "Embellish ",
      "Enigmatic ",
      "Ephemeral ",
      "Eradicate ",
      "Exorbitant ",
      "Flamboyant ",
      "Fluctuate ",
      "Fortitude ",
      "Frivolous ",
      "Fabricate ",
      "Garrulous ",
      "Gregarious ",
      "Grotesque ",
      "Grandiose ",
      "Harbinger ",
      "Haughty ",
      "Heinous ",
      "Homogeneous ",
      "Hypocrisy ",
      "Hypothetical ",
      "Haphazard ",
      "Harrowing ",
      "Illustrious ",
      "Immaculate ",
      "Impartial ",
      "Implacable ",
      "Incessant ",
      "Indomitable ",
      "Jubilant ",
      "Judicious ",
      "Juxtapose ",
      "Labyrinth ",
      "Luminous ",
      "Lucrative ",
      "Longevity ",
      "Malevolent ",
      "Magnanimous ",
      "Maverick ",
      "Melancholy ",
      "Meticulous ",
      "Misconstrue ",
      "Multifaceted ",
      "Munificent ",
      "Negligible ",
      "Omnipotent ",
      "Overwhelm ",
      "Omnipresent ",
      "Orthodox ",
      "Paradoxical ",
      "Parchment ",
      "Phenomenal ",
      "Pretentious ",
      "Predicament ",
      "Proficient ",
      "Prominent ",
      "Prosperous ",
      "Protagonist ",
      "Provincial",
      "Reciprocity ",
      "Resonance ",
      "Resourceful ",
      "Reverence ",
      "Serendipity ",
      "Tentative ",
      "Unwavering ",
      "Transient ",
      "Theoretical ",
      "Predominant ",
      "Palatable ",
    ],
  },
  super: {
    [LEVELS.Final]: [
      "Incomprehensibilities ",
      "uncopyrightable ",
      "Counterdemonstration ",
      "Uncharacteristically ",
      "Institutionalisation ",
      "Microseismograph ",
      "Nonrepresentationalism ",
      "Overinterpretations ",
      "Counterrevolutionaries ",
      "Unenthusiastically ",
      "Overintellectualised ",
      "Hyperresponsibility ",
      "Phenomenologically ",
      "Disproportionately ",
      "Electromagnetically ",
      "Resourcefulness ",
      "Disequilibrium",
      "unpronounceable ",
      "Semimanufactures",
      "Subterranean",
      "Tintinnabulation",
      "Pharmaceutical ",
      "Hyperpyrexia",
      "Transubstantiation",
      "Chrysanthemum",
      "Imprescriptible",
      "Staphylococcus",
      "Inconsequential",
      "Triskaidekaphobia ",
      "humanitarianism ",
      "crystallomancy",
      "applicableness",
      "autocurriculum",
      "experimentation",
      "logarithmically",
      "distinguishable",
      "mechanochemical",
      "methamphetamine",
      "monopathophobia",
      "purposelessness",
      "quadruplication",
      "quarrelsomeness",
      "transmissometer",
      "trustworthiness",
      "synergistically",
      "photodetachment",
      "redetermination",
      "reprecipitation",
      "multiculturalism",
      "quarkochemistry",
    ],
  },
};

